# Stage 1: Base image
FROM python:3.9-slim AS base

# Set working directory
WORKDIR /app

# Stage 2: Builder image
FROM base AS builder

# Install build dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends build-essential

# Install Python dependencies
COPY app/requirements.txt .
RUN pip install --upgrade pip && \
    pip install --no-cache-dir --user -r requirements.txt

# Stage 3: Final image
FROM base

# Copy Python dependencies from the builder stage
COPY --from=builder /root/.local /root/.local

# Make sure scripts in .local are usable:
ENV PATH=/root/.local/bin:$PATH

# Copy application files
COPY app /app

# Expose the application port
EXPOSE 5000

# Start the application
CMD ["python", "app.py"]
